### PR TITLE
Feat set/get list on localStorage

### PR DESCRIPTION
**Pull request by mixcas**

### CODE REVIEW

**Comment by varffs** [comment]
Should there not be an expiration on this stored value? Should we not also set a timestamp and check 24 hours and regenerate afterwards?

**Comment by mixcas** [comment]
@varffs where r u getting that spec from?

**Comment by varffs** [comment]
Its not a spec its a question. It was prompted by me running dev mode and realizing that once set this value will last as longer as the browser.

**Comment by mixcas** [comment]
Thats the expected behavior

**Comment by varffs** [comment]
Ok. Well I think you should add something to dev mode that sets the saved value to `null`

**Comment by mixcas** [comment]
I thought about it, but that's not always the desired behaviour when developing. If u need to clear it u can manually do it in  Dev Tools > Application > Clear Storage

**Pull request merged**
